import Foundation

struct CAMLAnim {
    var keyPath: String
    var values: [Double]
    var keyTimes: [Double]? = nil
    var duration: Double
    var beginTime: Double = 0
    var timeOffset: Double = 0
    var autoreverses: Bool = false
    var repeatForever: Bool = true
    var timingFunction: String = "linear"
}

struct WallpaperProperty {
    var keyPath: String
    var layerName: String
    var view: String
    var vLock: Double
    var vHome: Double
    var vSleep: Double
}

struct CAMLItem {
    var id: String
    var name: String
    var assetFile: String
    var boundsW: Double
    var boundsH: Double
    var centerX: Double
    var centerY: Double
    var rotationZ: Double
    var opacity: Double
    var blend: BlendMode
    var anims: [CAMLAnim] = []
}

enum CAML {
    static let assetManifest = """
    <?xml version="1.0" encoding="UTF-8"?>

    <caml xmlns="http://www.apple.com/CoreAnimation/1.0">
      <MicaAssetManifest>
        <modules type="NSArray"/>
      </MicaAssetManifest>
    </caml>
    """

    static func indexXML(docW: Double, docH: Double) -> String {
        """
        <?xml version="1.0" encoding="UTF-8"?>
        <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
        <plist version="1.0">
        <dict>
        \t<key>assetManifest</key>
        \t<string>assetManifest.caml</string>
        \t<key>documentHeight</key>
        \t<real>\(fmt(docH))</real>
        \t<key>documentResizesToView</key>
        \t<false/>
        \t<key>documentWidth</key>
        \t<real>\(fmt(docW))</real>
        \t<key>geometryFlipped</key>
        \t<false/>
        \t<key>loopEnd</key>
        \t<real>+infinity</real>
        \t<key>loopStart</key>
        \t<real>0.0</real>
        \t<key>loopingEnabled</key>
        \t<true/>
        \t<key>rootDocument</key>
        \t<string>main.caml</string>
        \t<key>scalesToFitInPlayer</key>
        \t<true/>
        </dict>
        </plist>
        """
    }

    static let indexXMLMinimal = """
    <?xml version="1.0" encoding="UTF-8"?>
    <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
    <plist version="1.0">
    <dict>
    \t<key>rootDocument</key>
    \t<string>main.caml</string>
    </dict>
    </plist>
    """

    static func parameterizedMain(docW: Double, docH: Double,
                                  background: [CAMLItem], floating: [CAMLItem],
                                  properties: [WallpaperProperty]) -> String {
        let cx = docW / 2, cy = docH / 2
        func container(id: String, name: String, _ items: [CAMLItem]) -> String {
            var subs = ""
            for it in items { subs += layerXML(it) }
            return """
                  <CALayer id="\(id)" name="\(name)" bounds="0 0 \(fmt(docW)) \(fmt(docH))" position="\(fmt(cx)) \(fmt(cy))" geometryFlipped="0" masksToBounds="0" opacity="1" transform="rotate(0deg)" cornerRadius="0" allowsEdgeAntialiasing="1" allowsGroupOpacity="1" contentsFormat="RGBA8" cornerCurve="circular">
                    <sublayers>
            \(subs)        </sublayers>
                  </CALayer>

            """
        }
        return """
        <?xml version="1.0" encoding="UTF-8"?>
        <!--
          Generated by PosterLab — .tendies wallpaper studio (ParameterizedCA)
        -->
        <caml xmlns="http://www.apple.com/CoreAnimation/1.0">
          <CALayer id="__capRootLayer__" name="Root Layer" bounds="0 0 \(fmt(docW)) \(fmt(docH))" position="\(fmt(cx)) \(fmt(cy))" geometryFlipped="0" opacity="1" transform="rotate(0deg)" backgroundColor="0 0 0 1" cornerRadius="0" allowsEdgeAntialiasing="1" allowsGroupOpacity="1" contentsFormat="RGBA8" cornerCurve="circular">
        \(styleXML(properties))    <sublayers>
        \(container(id: "background", name: "BACKGROUND", background))\(container(id: "floating", name: "FLOATING", floating))    </sublayers>
          </CALayer>
        </caml>
        """
    }

    static func mainCAML(docW: Double, docH: Double, items: [CAMLItem],
                         properties: [WallpaperProperty] = []) -> String {
        let cx = docW / 2, cy = docH / 2
        var sublayers = ""
        for item in items {
            sublayers += layerXML(item)
        }
        return """
        <?xml version="1.0" encoding="UTF-8"?>
        <!--
          Generated by PosterLab — .tendies wallpaper studio
        -->
        <caml xmlns="http://www.apple.com/CoreAnimation/1.0">
          <CALayer id="__capRootLayer__" name="Root Layer" bounds="0 0 \(fmt(docW)) \(fmt(docH))" position="\(fmt(cx)) \(fmt(cy))" geometryFlipped="0" opacity="1" transform="rotate(0deg)" backgroundColor="0 0 0 0" cornerRadius="0" allowsEdgeAntialiasing="1" allowsGroupOpacity="1" contentsFormat="RGBA8" cornerCurve="circular">
        \(styleXML(properties))    <sublayers>
        \(sublayers.isEmpty ? "" : sublayers)    </sublayers>
          </CALayer>
        </caml>
        """
    }

    private static func styleXML(_ properties: [WallpaperProperty]) -> String {
        guard !properties.isEmpty else { return "" }
        var groups = ""
        for p in properties {
            groups += """
                    <NSDictionary>
                      <image type="null"/>
                      <keyPath type="string" value="\(p.keyPath)"/>
                      <layerName type="string" value="\(xmlEscape(p.layerName))"/>
                      <v_home type="real" value="\(fmt(p.vHome))"/>
                      <v_lock type="real" value="\(fmt(p.vLock))"/>
                      <v_sleep type="real" value="\(fmt(p.vSleep))"/>
                      <view type="string" value="\(p.view)"/>
                    </NSDictionary>

            """
        }
        return """
            <style>
              <wallpaperBackgroundAssetNames type="NSArray"/>
              <wallpaperFloatingAssetNames type="NSArray"/>
              <wallpaperParallaxGroups type="NSArray"/>
              <wallpaperPropertyGroups type="NSArray">
        \(groups)      </wallpaperPropertyGroups>
            </style>

        """
    }

    private static func layerXML(_ i: CAMLItem) -> String {
        let deg = i.rotationZ * 180 / .pi
        let blendXML = i.blend == .normal ? "" :
            "\n          <compositingFilter type=\"CAFilter\" filter=\"\(i.blend.rawValue)\" name=\"\(i.blend.rawValue)\"/>"
        let animXML = i.anims.isEmpty ? "" : animsXML(i.anims)
        return """
              <CALayer id="\(i.id)" name="\(xmlEscape(i.name))" bounds="0 0 \(fmt(i.boundsW)) \(fmt(i.boundsH))" position="\(fmt(i.centerX)) \(fmt(i.centerY))" geometryFlipped="0" masksToBounds="0" opacity="\(fmt(i.opacity))" transform.rotation.z="\(fmt(i.rotationZ))" transform="rotate(\(fmt(deg))deg)" cornerRadius="0" allowsEdgeAntialiasing="1" allowsGroupOpacity="1" contentsFormat="RGBA8" cornerCurve="circular">\(blendXML)
                <contents>
                  <CGImage src="assets/\(i.assetFile)"/>
                </contents>\(animXML)
              </CALayer>

        """
    }

    private static func animsXML(_ anims: [CAMLAnim]) -> String {
        var inner = ""
        for (idx, a) in anims.enumerated() {
            let begin = a.beginTime == 0 ? "1e-100" : fmt(a.beginTime)
            let timeOffsetAttr = a.timeOffset != 0 ? " timeOffset=\"\(fmt(a.timeOffset))\"" : ""
            let repeatAttrs = a.repeatForever
                ? "repeatCount=\"inf\" repeatDuration=\"inf\" fillMode=\"both\""
                : "repeatCount=\"1\" fillMode=\"both\""
            let valuesXML = a.values.map { "              <real value=\"\(fmt($0))\"/>" }.joined(separator: "\n")
            let keyTimesXML: String
            if let kts = a.keyTimes, kts.count == a.values.count {
                let items = kts.map { "              <real value=\"\(fmt($0))\"/>" }.joined(separator: "\n")
                keyTimesXML = """

                    <keyTimes>
            \(items)
                    </keyTimes>
            """
            } else {
                keyTimesXML = ""
            }
            inner += """
                  <animation key="animation-\(idx)" type="CAKeyframeAnimation" keyPath="\(a.keyPath)" autoreverses="\(a.autoreverses ? 1 : 0)" beginTime="\(begin)"\(timeOffsetAttr) duration="\(fmt(a.duration))" removedOnCompletion="0" \(repeatAttrs) calculationMode="linear" timingFunction="\(a.timingFunction)">
                    <values>
            \(valuesXML)
                    </values>\(keyTimesXML)
                  </animation>

            """
        }
        return """

                <animations>
            \(inner)    </animations>
        """
    }

    private static func fmt(_ v: Double) -> String {
        if v == v.rounded() && abs(v) < 1e15 {
            return String(format: "%g", v)
        }
        return String(format: "%.6g", v)
    }

    private static func xmlEscape(_ s: String) -> String {
        s.replacingOccurrences(of: "&", with: "&amp;")
            .replacingOccurrences(of: "<", with: "&lt;")
            .replacingOccurrences(of: ">", with: "&gt;")
            .replacingOccurrences(of: "\"", with: "&quot;")
    }
}
